service: ml-playground-log-stream-service

provider:
  name: google
  stage: dev
  runtime: python38
  region: asia-northeast1
  project: ml-playground-306716
  credentials: ${env:CREDENTIALS_PATH}
  # TODO ローカルでも環境変数を利用する
  # credentials: ~/.gcloud/keys/ml-playground-log-stream.json

frameworkVersion: "2"
plugins:
  - serverless-google-cloudfunctions
  - serverless-python-requirements
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  extract:
    handler: extract_logs
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/ml-playground-306716/topics/ml-playground-log-export-topic
    environment:
      GCP_PROJECT_ID: ${env:GCP_PROJECT_ID}

custom:
  pythonRequirements:
    pythonBin: python3
