name: Check Code

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Add path for Poetry
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install Dependencies
        run: poetry install
      # - name: Check flake8
      #   run: poetry run flake8 src/app --ignore E501,E128
      # - name: Check mypy
      #   run: poetry run mypy src/app --ignore-missing-imports --show-column-numbers --check-untyped-defs
      - name: Unit test
        run: poetry run pytest tests -v --cov=.
        env:
          BATCH_LOG_LEVEL: info
